version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always 
        ports:
          - "80:80"
          - "${CLIENT_PORT}:443"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}
    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf    
    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes: 
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      command: certonly --webroot -w /var/www/certbot --force-renewal --email craft_89@inbox.ru -d bug-and-play-flappy-bird-21.ya-praktikum.tech --agree-tos
    
    postgres:
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      healthcheck:
        test: "exit 0"
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        depends_on:
          - postgres
        restart: always
        ports:
            - "3001:3001"
        environment:
          SERVER_PORT: 3001
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_DB: ${POSTGRES_DB}
