version: "3.9"

services:
  client:
    container_name: prakticum-client
    image: prakticum-client
    build:
        context: .
        dockerfile: Dockerfile.client
        args:
          CLIENT_PORT: ${CLIENT_PORT}
    restart: always 
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "${CLIENT_PORT}:443"
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVER_PORT=${SERVER_PORT}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
    postgres:
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      healthcheck:
        test: "exit 0"
    server:
      container_name: prakticum-server
      image: prackicum-server
      build:
          context: .
          dockerfile: Dockerfile.server
          args:
            SERVER_PORT: ${SERVER_PORT}
      depends_on:
        - postgres
      restart: always
      ports:
          - "3001:3001"
      environment:
        SERVER_PORT: 3001
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
