name: Deploy code on server

on: [push]

permissions:
  contents: read

jobs:
  deploy:
    name: deploy

    runs-on: ubuntu-latest
    steps:
      - name: Deploy code on the remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/Flappy-bird/
            git pull origin BAP-61
            git checkout origin BAP-61
            cp .env.sample .env
            mkdir -p tmp/pgdata
            docker compose up --build -d
